module.exports = {
  siteMetadata: {
    title: 'Martin Reiche - Full Stack Web Developer',
    descriptionDe: 'Full Stack Webentickler und Data Scientist.',
    descriptionEn: 'Full stack web developer and data scientist.',
    keywords: {
      de: [
        'Webentwickler',
        'Webentwicklung',
        'Data Scientist',
        'DevOps',
        'CI/CD',
        'Kubernetes',
        'Progressive Web Apps',
        'Programmierer',
        'Javascript',
        'Python',
        'Node.js',
        'React.js',
        'Graphql',
        'Electron',
      ],
      en: [
        'web developer',
        'web development',
        'data scientist',
        'DevOps',
        'CI/CD',
        'Kubernetes',
        'Progressive Web Apps',
        'programmer',
        'Javascript',
        'Python',
        'Node.js',
        'React.js',
        'Graphql',
        'Electron',
        'Angular',

      ],
    },
    author: `Martin Reiche`,
  },
  plugins: [
    `gatsby-plugin-top-layout`,
    `gatsby-plugin-material-ui`,
    `gatsby-plugin-react-helmet`,
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `images`,
        path: `${__dirname}/src/images`,
      },
    },
    `gatsby-transformer-sharp`,
    `gatsby-plugin-sharp`,
    {
      resolve: `gatsby-plugin-manifest`,
      options: {
        name: `Martin Reiche - Fullstack Web Developer`,
        short_name: `Martin Reiche`,
        start_url: `/`,
        background_color: `#fafafa`,
        theme_color: `#008090`,
        display: `minimal-ui`,
        icon: `src/images/favicon.png`, // This path is relative to the root of the site.
      },
    },
  ],
};
